### ISSUE TITLE
部署linux mongodb集群 但是会报错

### ISSUE THREAD

**Issue by bandow** [wangweianger/zanePerfor#54]
(node:2611) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
2021-03-29 17:17:00,029 ERROR 2611 [Job#16170094200012871372976768671] /opt/zanePerfor/app/schedule/ip_task.js execute failed, used 24ms. { MongoError: not authorized on performance to execute command { distinct: "systems", key: "app_id", query: { type: "web" }, lsid: { id: UUID("79941e64-2b5d-4d1f-86e7-e3566568f319") }, $clusterTime: { clusterTime: Timestamp(1617009402, 4), signature: { hash: BinData(0, 502F7D5161F5E86197502542CD3B17E5B8C87787), keyId: 6943851795571539994 } }, $db: "performance", $readPreference: { mode: "secondaryPreferred" } }
    at Connection.<anonymous> (/opt/zanePerfor/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (events.js:182:13)
    at processMessage (/opt/zanePerfor/node_modules/mongodb/lib/core/connection/connection.js:451:10)
    at Socket.<anonymous> (/opt/zanePerfor/node_modules/mongodb/lib/core/connection/connection.js:620:15)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
  ok: 0,
  code: 13,
  codeName: 'Unauthorized',
  operationTime:
   Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1617009402 },
  '$clusterTime':
   { clusterTime:
      Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1617009402 },
     signature: { hash: [Binary], keyId: [Long] } },
  name: 'MongoError' }
2021-03-29 17:17:00,037 INFO 2611 重启db3数据库失败!

**Comment by bandow** [comment]
页面上登录或者注册 会提示这个报错
Mongonot authorized on performance to execute command { find: "users", filter: { user_name: "admin" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, lsid: { id: UUID("79941e64-2b5d-4d1f-86e7-e3566568f319") }, $clusterTime: { clusterTime: Timestamp(1617010042, 1), signature: { hash: BinData(0, FA1F6998AF260FEC41511F419023AB34D4C9CB64), keyId: 6943851795571539994 } }, $db: "performance" }

**Comment by wangweianger** [comment]
看你这个提示是 mongo 数据库没有权限，去尝试如何设置数据库访问权限
