### ISSUE TITLE
api/v1/report/webscript 接口404

### ISSUE THREAD

**Issue by jiangzhenxiang** [wangweianger/zanePerfor#9]
本地启动服务，http://127.0.0.1:7001/api/v1/report/webscript接口404，http://127.0.0.1:7001/api/v1/report/web 同样404
```
<\script src="/dist/performance-report-default.min.js"><\/script>
<\script>
Performance({
    domain: 'http://127.0.0.1:7001/api/v1/report/webscript', 
    add:{
        appId:'pwBSn621542855731693'
    }
})
<\/script>
```
难道domain不是这个吗

**Comment by jiangzhenxiang** [comment]
本地启动服务，http://127.0.0.1:7001/api/v1/report/webscript接口404，http://127.0.0.1:7001/api/v1/report/web 同样404

````
<\script src="/dist/performance-report-default.min.js"><\/script>
<\script>
Performance({
    domain: 'http://127.0.0.1:7001/api/v1/report/webscript', 
    add:{
        appId:'pwBSn621542855731693'
    }
})
<\/script>
```
难道domain不是这个吗

**Comment by wangweianger** [comment]
@jiangzhenxiang   你好webscript接口已经删除  只有 /api/v1/report/web这个接口 可用，项目只能使用sdk上报，404错误应该是你的服务没有启动成功

**Comment by jiangzhenxiang** [comment]
> @jiangzhenxiang 你好webscript接口已经删除 只有 /api/v1/report/web这个接口 可用，项目只能使用sdk上报，404错误应该是你的服务没有启动成功

npm run dev启动成功，能够进入后台。
但 /api/v1/report/web接口是404，请问怎么能排查我这个接口是否启动成功？
另外我npm install时报错
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [librdkafka.1.dylib] Error 1
make[1]: *** [libs] Error 2
make: *** [11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate] Error 2
rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jiangzhenxiang/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/jiangzhenxiang/.nvm/versions/node/v8.12.0/bin/node" "/Users/jiangzhenxiang/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /github/zanePerfor/node_modules/node-rdkafka
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN co-mocha@1.2.2 requires a peer of mocha@>=1.18 <6 but none is installed. You must install peer dependencies yourself.
npm WARN espower-typescript@9.0.1 requires a peer of typescript@>= 2.4.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jiangzhenxiang/.npm/_logs/2018-11-22T09_10_45_781Z-debug.log
```
不知道是否有影响，

**Comment by jiangzhenxiang** [comment]
@wangweianger 请问，有什么办法排查 /api/v1/report/web这个接口是否启动成功吗？
我在本地和我的阿里云服务器上执行npm run dev没有问题，能够访问到后台页面，就是上报信息的接口404.

**Comment by jiangzhenxiang** [comment]
已解决谢谢

**Comment by wy281704862** [comment]
@jiangzhenxiang 怎么解决的？  我也遇到跟你相同的问题

**Comment by wy281704862** [comment]
谢谢，我已经解决了。换成api/v1/report/web 这个接口地址就可以了

**Comment by jiangzhenxiang** [comment]
@wangweianger 好的谢谢
